name: Waka Readme

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_URL: ${{ secrets.WAKATIME_API_URL }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_USERNAME: "github-actions[bot]"
          COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          # IGNORED_REPOS: "repo1, repo2"

          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          # SHOW_EDITORS: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_PROJECTS: "False"
          SHOW_LOC_CHART: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_UPDATED_DATE: "True"
          UPDATED_DATE_FORMAT: "%Y/%m/%d %H:%M:%S"
